name: FootballHub API CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Add app to Python path
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        pytest tests/
        
    - name: Verify server startup
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 3
        curl -s http://localhost:8000 | grep "Hello" || exit 1
        kill %1
